In [ ]:
!nvidia-smi

Tue Jan  6 05:39:41 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#00. Pytorch Notebook
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vec = torch.tensor([10,10])
vec

tensor([10, 10])

In [ ]:
vec.ndim

1

In [ ]:
vec.shape

torch.Size([2])

In [ ]:
mat = torch.tensor([[2,3],[4,5]])
mat

tensor([[2, 3],
        [4, 5]])

In [ ]:
mat.ndim

2

In [ ]:
mat1 = torch.tensor([[2,4,6],[3,5,7],[4,6,8]])
mat1.ndim

2

In [ ]:
mat.shape

torch.Size([2, 2])

In [ ]:
mat1.shape

torch.Size([3, 3])

In [ ]:
ten = torch.tensor([[[3,4,5],[2,3,4],[6,7,8]]])
ten

tensor([[[3, 4, 5],
         [2, 3, 4],
         [6, 7, 8]]])

In [ ]:
ten.ndim

3

In [ ]:
ten.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor = torch.rand(3,2)
random_tensor

tensor([[0.2146, 0.6436],
        [0.0385, 0.6032],
        [0.6301, 0.4981]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor = torch.rand(2,2,2)
random_tensor

tensor([[[0.5050, 0.9769],
         [0.7813, 0.3526]],

        [[0.3905, 0.5745],
         [0.1053, 0.9191]]])

In [ ]:
# (height, width, colour_channels)
image_size_tensor = torch.rand(size = (224,224,3))
image_size_tensor.shape, image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
mat.dtype

torch.int64

In [ ]:
torch.ones(size=(4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating range of tensors

In [ ]:
odd = torch.arange(1,10,step=2)
odd

tensor([1, 3, 5, 7, 9])

In [ ]:
ten_zeroes = torch.zeros_like(input = odd)
ten_zeroes

tensor([0, 0, 0, 0, 0])

In [ ]:
torch.full_like(fill_value= 1, input = odd, dtype=odd.dtype)

tensor([1, 1, 1, 1, 1])

## Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad=False)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
int_32_tensor = torch.tensor([2.0,4,5.0],
                             dtype = torch.int32)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
ans = float_32_tensor/int_32_tensor

In [ ]:
ans

tensor([1.5000, 1.5000, 1.8000])

In [ ]:
ans.dtype

torch.float32

## Getting Information from tensors

1. Tensors not right datatype - tensor.dtype

2. Tensors not right shape - tensor.shape

3. Tensors not on right device - to get device from a tensor - tensor.device

In [ ]:
mat.device

device(type='cpu')

### Tensor Operation

In [ ]:
x = torch.tensor([1,2,3])
x + 10

tensor([11, 12, 13])

In [ ]:
x-1

tensor([0, 1, 2])

In [ ]:
x*10

tensor([10, 20, 30])

In [ ]:
#pytorch in-built funtion
torch.mul(x,10)

tensor([10, 20, 30])

## Matrix Multiplication

In [ ]:
X = torch.tensor([[1,2],[3,4]])
X

tensor([[1, 2],
        [3, 4]])

In [ ]:
X*2

tensor([[2, 4],
        [6, 8]])

In [ ]:
Y = torch.tensor([[1,1],[1,1]])
Y

tensor([[1, 1],
        [1, 1]])

In [ ]:
X*Y

tensor([[1, 2],
        [3, 4]])

In [ ]:
torch.matmul(X,Y)

tensor([[3, 3],
        [7, 7]])

In [ ]:
x = torch.tensor([[1,1,2]])
x

tensor([[1, 1, 2]])

In [ ]:
y = torch.tensor([[1],[1],[2]])
y

tensor([[1],
        [1],
        [2]])

In [ ]:
y.shape

torch.Size([3, 1])

In [ ]:
print(f"{x.shape}")

torch.Size([1, 3])


In [ ]:
ans = torch.matmul(x,y)

In [ ]:
ans

tensor([[6]])

In [ ]:
ans.size()

torch.Size([1, 1])

In [ ]:
x = torch.tensor([1,2,3])

In [ ]:
%%time
value = 0
for i in range(len(x)):
  value += x[i]*x[i]
value

CPU times: user 1.19 ms, sys: 25 µs, total: 1.21 ms
Wall time: 1.07 ms


tensor(14)

In [ ]:
%%time
torch.matmul(x,x)

CPU times: user 0 ns, sys: 1.16 ms, total: 1.16 ms
Wall time: 7.91 ms


tensor(14)

In [ ]:
x*x

tensor([1, 4, 9])

In [ ]:
torch.matmul(x,x)

tensor(14)

In [ ]:
x @ x

tensor(14)

In [ ]:
x.ndim

1

In [ ]:
x

tensor([1, 2, 3])

In [ ]:
A = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])

In [ ]:
B = torch.tensor([[7,10],
                  [8,11],
                  [9,12]])

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([2,4,6])

In [ ]:
torch.mm(A, B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
A @ B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregation

#### finding max, min, sum, mean, etc.

In [ ]:
x = torch.arange(0,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes the input tensor into defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal torch.tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - remove all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimenstion to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x(because a view of a tensor share the same memory as the original input)

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor

x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
y = torch.rand(size=(2,3,1,2,1,1))

In [ ]:
y_squeezed = y.squeeze()

In [ ]:
y.shape, y_squeezed.shape

(torch.Size([2, 3, 1, 2, 1, 1]), torch.Size([2, 3, 2]))

In [ ]:
y_squeezed.unsqueeze(dim = 2).shape

torch.Size([2, 3, 1, 2])

In [ ]:
y.unsqueeze(dim=1).shape

torch.Size([2, 1, 3, 1, 2, 1, 1])

In [ ]:
s = torch.rand(2)
s, s.shape

(tensor([0.4225, 0.7896]), torch.Size([2]))

In [ ]:
us = s.unsqueeze(dim=1)
us, us.shape

(tensor([[0.4225],
         [0.7896]]),
 torch.Size([2, 1]))

In [ ]:
s.reshape(2,1)

tensor([[0.4225],
        [0.7896]])

In [ ]:
r = torch.randn(size=(3,2,1))
r.size()

torch.Size([3, 2, 1])

In [ ]:
r

tensor([[[-0.4917],
         [ 0.6328]],

        [[ 0.2866],
         [-1.1016]],

        [[-1.5473],
         [ 0.8563]]])

In [ ]:
torch.permute(r, (1,2,0))

tensor([[[-0.4917,  0.2866, -1.5473]],

        [[ 0.6328, -1.1016,  0.8563]]])

## Observing how things work

In [ ]:
r = torch.arange(6)
r

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
r.shape

torch.Size([6])

In [ ]:
r.reshape(1,6)

tensor([[0, 1, 2, 3, 4, 5]])

In [ ]:
r.unsqueeze(dim=0)

tensor([[0, 1, 2, 3, 4, 5]])

In [ ]:
X = torch.rand(size = (2,3))
X

tensor([[0.7755, 0.6224, 0.9864],
        [0.4857, 0.6450, 0.6545]])

In [ ]:
X.unsqueeze(dim =2)

tensor([[[0.7755],
         [0.6224],
         [0.9864]],

        [[0.4857],
         [0.6450],
         [0.6545]]])

In [ ]:
X.reshape(2,3,1)

tensor([[[0.7755],
         [0.6224],
         [0.9864]],

        [[0.4857],
         [0.6450],
         [0.6545]]])

In [ ]:
r

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
r.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
r

tensor([0, 1, 2, 3, 4, 5])

## Indexing Tensors

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# x[0,0,1] or x[0][0][1]
x[0,0,1]

tensor(2)

In [ ]:
# ":" to select all of target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[0,1,1]

tensor(5)

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,:,0]

tensor([1, 4, 7])

In [ ]:
# to return 9
x[0,2,2]

tensor(9)

In [ ]:
#to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensors and Numpy

In [ ]:
import numpy as np
arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr)
arr, tensor

## while converting from numpy to, pytorch reflects numpy's
## default datatype of float64 unless specified otherwise

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
arr = arr + 1
arr

array([2., 3., 4., 5., 6., 7., 8.])

In [ ]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
## torch default is float32, as you change it to numpy the same reflects, so we have to change based on the task we are going to perform

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

* to reduce randomness in neural networks and pytorch comes with the concept of random torch.seed

In [ ]:
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)
## not reproducible

tensor([[0.4746, 0.6520, 0.1572, 0.6410],
        [0.6310, 0.8414, 0.2648, 0.5550],
        [0.8949, 0.3427, 0.2821, 0.3319]])
tensor([[0.1857, 0.4236, 0.6691, 0.9390],
        [0.8351, 0.8956, 0.5004, 0.2774],
        [0.3531, 0.0847, 0.9275, 0.6868]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

#1
torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3,4)

#2
torch.manual_seed(RANDOM_SEED)
random_tensorD = torch.rand(3,4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)
##reproducible

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Ways to Access GPU

* Google Colab
* Using own GPU
* Use cloud computing - GCP, AWS

In [ ]:
!nvidia-smi

Tue Jan  6 07:10:30 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   30C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
## check for gpu access using pytorch

torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

for faster computations

In [ ]:
x = torch.arange(1,4)
x, x.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
#move tensor to GPU (if available)
xgpu = x.to(device)
xgpu, xgpu

(tensor([1, 2, 3], device='cuda:0'), tensor([1, 2, 3], device='cuda:0'))

In [ ]:
## if tensors are on GPU, you cant convert them into NUMPY
xgpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#moving tensors back to CPU and then converting it into numpy
xcpu = x.cpu().numpy()
xcpu

array([1, 2, 3])